name: estimate
description: Estimate app.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_slidable: ^2.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pdf: ^3.8.4
  printing: ^5.9.3
  shared_preferences: ^2.0.15
  slide_to_act: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
